ALTER TABLE `skills` DROP `exp`;

ALTER TABLE `skills`
ADD `condition1` SMALLINT NOT NULL DEFAULT '1',
ADD `condition2` SMALLINT NOT NULL DEFAULT '1',
ADD `condition3` SMALLINT NOT NULL DEFAULT '1',
ADD `condition4` SMALLINT NOT NULL DEFAULT '1',
ADD `condition5` SMALLINT NOT NULL DEFAULT '1',
ADD `condition6` SMALLINT NOT NULL DEFAULT '1',
ADD `condition7` SMALLINT NOT NULL DEFAULT '1',
ADD `condition8` SMALLINT NOT NULL DEFAULT '1',
ADD `condition9` SMALLINT NOT NULL DEFAULT '1';
